---
- name: make directory if not exists
  shell: mkdir -p ~/apexdv_blog_api

- name: copy archived arifact
  copy:
    src: files/
    dest: /home/dev/apexdv_blog_api
    mode: 0644
    owner: dev
    group: dev

- name: unarchive artifact
  shell: |
    cd ~/apexdv_blog_api
    rm -rf .next
    tar -xvf artifact.tar.gz
    rm -rf artifact.tar.gz

- name: stop old pm2 process
  command: pm2 delete apexdv_blog_api
  ignore_errors: true

- name: create systemd service for the app
  template:
    src: apexdv_blog_api.service.j2
    dest: /etc/systemd/system/apexdv_blog_api/apexdv_blog_api.service
  notify: restart systemd service

- name: copy env file
  template:
    src: .env.j2
    dest: ~/apexdv_blog_api/.env

- name: copy nginx config file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/apexdv_blog_api

- name: enable nginx config
  shell: |
    ln -s /etc/nginx/sites-available/apexdv_blog_api /etc/nginx/sites-enabled/apexdv_blog_api
    nginx -t
    systemctl restart nginx

- name: start app
  shell: |
    ls -al
    cd ~/apexdv_blog_api
    npm run build
    system
    # pm2 start npm --name "apexdv_blog_api" -- start -- --port=3331
    # pm2 save
  notify: start systemd service
